### ISSUE TITLE
Error when running commands

### ISSUE THREAD

**Issue by Jovantri10** [adriansteffan/DiscordJockey#2]
![20200814_105022](https://user-images.githubusercontent.com/51161901/90211856-1a4e2180-de1c-11ea-9434-f132689d4c72.jpg)
when am run the commands, always like this, pls fix this owo

**Comment by adriansteffan** [comment]
Thanks for your interest in the project. I am currently no longer working on this, as I have moved on to work on the [discord-community-soundboard](https://github.com/adriansteffan/discord-community-soundboard) for now. It is still a WIP, but the discord.py side of things should be more stable. Otherwise, feel free to submit a PR if you find a fix here.

**Comment by Jovantri10** [comment]
Okay sure, thank you 😎♥♥
